BASE_URL = 'https://api.telegram.org/bot'

LOG_DIR = 'logs'

# Available languages configuration
AVAILABLE_LANGUAGES = [
    'EN', 'ES', 'FR', 'DE', 'IT', 'PT', 'RU', 'JA', 'KO', 'ZH', 'AR', 'HI', 'BN', 'UR', 'TR', 
    'NL', 'SV', 'DA', 'NO', 'FI', 'PL', 'CS', 'SK', 'HU', 'RO', 'BG', 'HR', 'SR', 'SL', 'ET', 
    'LV', 'LT', 'MT', 'GA', 'CY', 'EU', 'CA', 'GL', 'IS', 'FO', 'SQ', 'MK', 'BS', 'ME', 'XH', 
    'ZU', 'AF', 'SW', 'AM', 'HE', 'FA', 'PS', 'KU', 'AZ', 'KA', 'HY', 'MN', 'TH', 'VI', 'ID', 
    'MS', 'TL', 'MY', 'KM', 'LO', 'NE', 'SI', 'TA', 'TE', 'KN', 'ML', 'GU', 'PA', 'OR', 'AS', 
    'MR', 'SA', 'BO', 'DZ', 'TI', 'SO', 'HA', 'IG', 'YO', 'ST', 'TN', 'TS', 'VE', 'XH', 'ZU'
]

AVAILABLE_LANGUAGES_DESCRIPTION = {
    'EN': 'English',
    'ES': 'Español (Spanish)',
    'FR': 'Français (French)',
    'DE': 'Deutsch (German)',
    'IT': 'Italiano (Italian)',
    'PT': 'Português (Portuguese)',
    'RU': 'Русский (Russian)',
    'JA': '日本語 (Japanese)',
    'KO': '한국어 (Korean)',
    'ZH': '中文 (Chinese)',
    'AR': 'العربية (Arabic)',
    'HI': 'हिन्दी (Hindi)',
    'BN': 'বাংলা (Bengali)',
    'UR': 'اردو (Urdu)',
    'TR': 'Türkçe (Turkish)',
    'NL': 'Nederlands (Dutch)',
    'SV': 'Svenska (Swedish)',
    'DA': 'Dansk (Danish)',
    'NO': 'Norsk (Norwegian)',
    'FI': 'Suomi (Finnish)',
    'PL': 'Polski (Polish)',
    'CS': 'Čeština (Czech)',
    'SK': 'Slovenčina (Slovak)',
    'HU': 'Magyar (Hungarian)',
    'RO': 'Română (Romanian)',
    'BG': 'Български (Bulgarian)',
    'HR': 'Hrvatski (Croatian)',
    'SR': 'Српски (Serbian)',
    'SL': 'Slovenščina (Slovenian)',
    'ET': 'Eesti (Estonian)',
    'LV': 'Latviešu (Latvian)',
    'LT': 'Lietuvių (Lithuanian)',
    'MT': 'Malti (Maltese)',
    'GA': 'Gaeilge (Irish)',
    'CY': 'Cymraeg (Welsh)',
    'EU': 'Euskara (Basque)',
    'CA': 'Català (Catalan)',
    'GL': 'Galego (Galician)',
    'IS': 'Íslenska (Icelandic)',
    'FO': 'Føroyskt (Faroese)',
    'SQ': 'Shqip (Albanian)',
    'MK': 'Македонски (Macedonian)',
    'BS': 'Bosanski (Bosnian)',
    'ME': 'Crnogorski (Montenegrin)',
    'XH': 'isiXhosa (Xhosa)',
    'ZU': 'isiZulu (Zulu)',
    'AF': 'Afrikaans',
    'SW': 'Kiswahili (Swahili)',
    'AM': 'አማርኛ (Amharic)',
    'HE': 'עברית (Hebrew)',
    'FA': 'فارسی (Persian)',
    'PS': 'پښتو (Pashto)',
    'KU': 'کوردی (Kurdish)',
    'AZ': 'Azərbaycan (Azerbaijani)',
    'KA': 'ქართული (Georgian)',
    'HY': 'Հայերեն (Armenian)',
    'MN': 'Монгол (Mongolian)',
    'TH': 'ไทย (Thai)',
    'VI': 'Tiếng Việt (Vietnamese)',
    'ID': 'Bahasa Indonesia (Indonesian)',
    'MS': 'Bahasa Melayu (Malay)',
    'TL': 'Tagalog (Filipino)',
    'MY': 'မြန်မာ (Burmese)',
    'KM': 'ខ្មែរ (Khmer)',
    'LO': 'ລາວ (Lao)',
    'NE': 'नेपाली (Nepali)',
    'SI': 'සිංහල (Sinhala)',
    'TA': 'தமிழ் (Tamil)',
    'TE': 'తెలుగు (Telugu)',
    'KN': 'ಕನ್ನಡ (Kannada)',
    'ML': 'മലയാളം (Malayalam)',
    'GU': 'ગુજરાતી (Gujarati)',
    'PA': 'ਪੰਜਾਬੀ (Punjabi)',
    'OR': 'ଓଡ଼ିଆ (Odia)',
    'AS': 'অসমীয়া (Assamese)',
    'MR': 'मराठी (Marathi)',
    'SA': 'संस्कृतम् (Sanskrit)',
    'BO': 'བོད་ཡིག (Tibetan)',
    'DZ': 'རྫོང་ཁ (Dzongkha)',
    'TI': 'ትግርኛ (Tigrinya)',
    'SO': 'Soomaali (Somali)',
    'HA': 'Hausa',
    'IG': 'Igbo',
    'YO': 'Yorùbá',
    'ST': 'Sesotho',
    'TN': 'Setswana',
    'TS': 'Xitsonga',
    'VE': 'Tshivenda'
}
